[root@ip-10-0-1-168 ec2-user]# cat install.yml
---
- name: Install Monitoring Tools and Docker on Amazon Linux
  hosts: localhost
  connection: local
  become: yes
  tasks:

    # --- 1. INSTALL DOCKER ---
    - name: Install Docker Engine
      yum:
        name: docker
        state: present
        update_cache: yes

    - name: Start and Enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add users to docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop:
        - ec2-user
        - jenkins
      ignore_errors: yes # In case Jenkins isn't installed yet

    # --- 2. GRAFANA (Using YUM) ---
    - name: Add Grafana Repository
      yum_repository:
        name: grafana
        description: Grafana Repository
        baseurl: https://rpm.grafana.com
        gpgcheck: yes
        gpgkey: https://rpm.grafana.com/gpg.key
        enabled: yes

    - name: Install Grafana
      yum:
        name: grafana
        state: present
    # --- 4. MANAGE SERVICES ---
    - name: Start and Enable Monitoring Services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - grafana-server
